### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by hillyleopard133**

### CODE REVIEW

**Review by evanhearne — CHANGES_REQUESTED** [review]
Needs to be merged with Student file already on repo

**Review by evanhearne — CHANGES_REQUESTED** [review]
Needs to be compared with StudentTest.java already on repo.

**Comment by evanhearne** [comment]
@hillyleopard133 did you mean to close the branch?

**Comment by hillyleopard133** [comment]
yes

**Comment by hillyleopard133** [comment]
i dont know how to change it easier just close it and open a new one so i didnt have to figure it out lol

**Comment by evanhearne** [comment]
@hillyleopard133 I would keep this PR open, edit the files requested, commit and push to your branch. Probably the easiest way to do this. :)

**Comment by hillyleopard133** [comment]
i already submitted the new one though

**Comment by evanhearne** [comment]
No problem, I reviewed the changes in the new PR. :)

**Pull request closed without merging**
